# Generated by Django 2.0.9 on 2018-12-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_auto_20181215_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='pay_amt_6',
            field=models.IntegerField(default=5000),
        ),
    ]
